server:
  port: 8090
spring:
  application:
    name: consul-consumer-payment
  cloud:
    consul:
      host: localhost
      post: 8500
      discovery:
        service-name: ${spring.application.name}